name: CI Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Tests
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.x'
        
    - name: Install dependencies
      working-directory: ./app
      run: npm ci # uses package-lock.json
      
    - name: Run Tests
      working-directory: ./app
      run: npm run test

    - name: Build Project
      working-directory: ./app
      run: npm run build --if-present
